# Generated by Django 4.2.5 on 2023-11-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ambrella', '0002_book'),
    ]

    operations = [

        migrations.AddField(
            model_name='students',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
    ]
