# Generated by Django 4.2.5 on 2023-11-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ambrella', '0003_remove_book_time_create_remove_book_time_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
